name: CI/CD Pipeline

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get short SHA
        id: sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/markdonaho/grow-tracker:latest
            ghcr.io/markdonaho/grow-tracker:${{ steps.sha.outputs.short_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
  update-gitops:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get short SHA
        id: sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - name: Checkout GitOps repository
        uses: actions/checkout@v3
        with:
          repository: markdonaho/k8s-gitops  
          token: ${{ secrets.GITOPS_PAT }}   
          path: k8s-gitops
          
      - name: Update Kubernetes manifests
        run: |
          cd k8s-gitops/workloads/growtracker
          # Replace the image tag in the deployment file
          sed -i "s|image: ghcr.io/markdonaho/grow-tracker:.*|image: ghcr.io/markdonaho/grow-tracker:${{ steps.sha.outputs.short_sha }}|g" 04-growtracker-deployment.yaml
          
      - name: Commit and push changes
        run: |
          cd k8s-gitops
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update GrowTracker image to ${{ steps.sha.outputs.short_sha }}" || echo "No changes to commit"
          git push